- hosts: "all"
   tasks:
          - name: configure yum for docker
             yum_repository:
                  name: Docker
                 description: Docker Repo
                 baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
                  gpgcheck: no

            - name: install docker software
              package:
                     name:  "docker-ce-18.09.1-3.el7.x86_64"
                     state: present

           - name: Starting docker service
             service:
                     name: "docker"
                     state: started
                     enabled: yes

           - name: Installing Python36
             package:
                   name: "python36"
                   state: present

            - name: Installing Docker SDK for python3
              command: pip3 install docker

          - name: Creating folder and copying html file
            file:
                     path: /html
                     state: directory


           - name: Copying html files
             copy:
                       src: "home.html"
                       dest: "/html/"

             - name: Creating container using HTTPD Image
                docker_container:
                              name: "mywebserver"
                              image: "httpd"
                              state: "started"
                              exposed_ports:
                                - "80"
                                ports:
                                 - "8888:80"
                                volumes:
                              - "/webpages:/usr/local/apache2/htdocs/"
